export const UNITS = {
  feet: {
    id: 'feet',
    name: 'Feet',
    label: 'Feet (ft)',
    symbol: 'ft',
    quoteSymbol: "'",
    areaSymbol: 'sq ft',
    factor: 1,
    toUnit: (feet) => feet,
    fromUnit: (val) => val,
    formatVal: (feet) => Math.round(feet).toString(),
    formatDim: (feet) => `${Math.round(feet)} FT`,
    formatDimShort: (feet) => `${Math.round(feet)}'`,
    formatDimRaw: (feet) => `${Math.round(feet)}`,
    formatRoom: (w, h) => `${Math.round(w)}FT X ${Math.round(h)}FT.`,
    legendItems: {
      door: "7' × 3'",
      mainDoor: "7' × 4.5'",
      window: "4' × 3.2'",
      vent: "2' × 2'",
      pillar: '10" × 10"',
    },
  },
  meters: {
    id: 'meters',
    name: 'Meters',
    label: 'Meters (m)',
    symbol: 'm',
    quoteSymbol: 'm',
    areaSymbol: 'sq m',
    factor: 0.3048,
    toUnit: (feet) => Number((feet * 0.3048).toFixed(1)),
    fromUnit: (meters) => Number((meters / 0.3048).toFixed(2)),
    formatVal: (feet) => (feet * 0.3048).toFixed(1),
    formatDim: (feet) => `${(feet * 0.3048).toFixed(1)} M`,
    formatDimShort: (feet) => `${(feet * 0.3048).toFixed(1)}m`,
    formatDimRaw: (feet) => `${(feet * 0.3048).toFixed(1)}m`,
    formatRoom: (w, h) => `${(w * 0.3048).toFixed(1)}M X ${(h * 0.3048).toFixed(1)}M.`,
    legendItems: {
      door: '2.1m × 0.9m',
      mainDoor: '2.1m × 1.4m',
      window: '1.2m × 1.0m',
      vent: '0.6m × 0.6m',
      pillar: '25cm × 25cm',
    },
  },
  inches: {
    id: 'inches',
    name: 'Inches',
    label: 'Inches (in)',
    symbol: 'in',
    quoteSymbol: '"',
    areaSymbol: 'sq in',
    factor: 12,
    toUnit: (feet) => Math.round(feet * 12),
    fromUnit: (inches) => Number((inches / 12).toFixed(2)),
    formatVal: (feet) => Math.round(feet * 12).toString(),
    formatDim: (feet) => `${Math.round(feet * 12)} IN`,
    formatDimShort: (feet) => `${Math.round(feet * 12)}"`,
    formatDimRaw: (feet) => `${Math.round(feet * 12)}"`,
    formatRoom: (w, h) => `${Math.round(w * 12)}IN X ${Math.round(h * 12)}IN.`,
    legendItems: {
      door: '84" × 36"',
      mainDoor: '84" × 54"',
      window: '48" × 38"',
      vent: '24" × 24"',
      pillar: '10" × 10"',
    },
  },
  yards: {
    id: 'yards',
    name: 'Yards',
    label: 'Yards (yd)',
    symbol: 'yd',
    quoteSymbol: 'yd',
    areaSymbol: 'sq yd',
    factor: 1 / 3,
    toUnit: (feet) => Number((feet / 3).toFixed(1)),
    fromUnit: (yards) => Number((yards * 3).toFixed(2)),
    formatVal: (feet) => (feet / 3).toFixed(1),
    formatDim: (feet) => `${(feet / 3).toFixed(1)} YD`,
    formatDimShort: (feet) => `${(feet / 3).toFixed(1)}yd`,
    formatDimRaw: (feet) => `${(feet / 3).toFixed(1)}yd`,
    formatRoom: (w, h) => `${(w / 3).toFixed(1)}YD X ${(h / 3).toFixed(1)}YD.`,
    legendItems: {
      door: '2.3yd × 1.0yd',
      mainDoor: '2.3yd × 1.5yd',
      window: '1.3yd × 1.1yd',
      vent: '0.7yd × 0.7yd',
      pillar: '0.3yd × 0.3yd',
    },
  },
};

export const getUnitConfig = (unitKey) => UNITS[unitKey] || UNITS.feet;
